# Assessment 1 Workings

## Question 3

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import matplotlib.patches as patches
import scipy.signal

In [2]:
# Question 3.1
input = np.array([[7,7,7,4,4],
                    [6,5,7,4,3],
                    [7,8,7,3,3],
                    [1,1,2,2,3],
                    [2,3,3,3,6]])

mask = np.array([[1,0,-1],
                 [1,0,-1],
                 [1,0,-1]])

output = scipy.signal.convolve2d(input, mask, mode='valid')
print(output)

[[  1  -9 -11]
 [  2  -5  -7]
 [  2  -4   0]]


In [6]:
answer = ''
for row in output:
    for i,char in enumerate(row):
        answer += str(char)
        if i!=2: answer += ','
    answer += ';'
print(answer)

1,-9,-11;2,-5,-7;2,-4,0;
