# Numpy Superfast Tutorial

In this tutorial we go through the basic capabilities of numpy. 

**Learning Outcomes**

1.	gain familiarity with important basic operations in numpy
2.	ability to conduct a simple matrices and arrays operations in numpy

Numpy is all about dealing with arrays efficiently. It allows us to manipulate big arrays in a fast and convenient way. We do not use built in python lists because they are slow for large arrays. Remember they allow for different types to coexist in a list. We pay less efficiency as a price for this built in flexibility. Numpy condenses all the capabilities of usual numerical packages or software such as MATLAB or R (if you are familiar with these). For more details see [official numpy quick start](https://numpy.org/doc/stable/user/quickstart.html).


First we always need to import the library that we want to use, in our case the library is numpy and for abbreviation we called it np. 

In [1]:
import numpy as np

Each time we want to invoke a function from numpy we do something like np.fun() where fun() is the name of the function that we want to call. For example, numpy has a function called arange() that is similar to the usual python range() function but produces iterable list in an efficient way.

In [2]:
a = np.arange(2,10)
print(a)

[2 3 4 5 6 7 8 9]


In [7]:
a = np.arange(4,10)  # multiply all by 10
b = np.arange(0, 9, 2)
print(a*10)
print(b)

[40 50 60 70 80 90]
[0 2 4 6 8]


In [5]:
ap = np.arange(5)**10  # raise all to the power of 10
print(ap)

[      0       1    1024   59049 1048576]


## We can now slice

In [19]:
print(a)
print(a[::2])

[4 5 6 7 8 9]
[4 6 8]


In [6]:
print(a[:-1]) # print all except the last element

[4 5 6 7 8]


In [7]:
print(a[:-2]) # print all except the last 2 elements

[4 5 6 7]


Although the following is not generally advisable in data science or machine learning, we can go through the elements of an array one by one. It is better and more Pythonic to manipulate the array as is without treating each element separately. This is called vectorisation and constitutes an important aspect of machine learning algorithms

In [20]:
for i in a:
    print(i)

4
5
6
7
8
9


## We can deal with multi-dimensional arrays

The following generates numbers 0<=x<1

In [21]:
rg = np.random.default_rng(1)     # for random number generation
a = rg.random((3,4))
print(a)

a = rg.random((3,4))
print(a)


[[0.51182162 0.9504637  0.14415961 0.94864945]
 [0.31183145 0.42332645 0.82770259 0.40919914]
 [0.54959369 0.02755911 0.75351311 0.53814331]]
[[0.32973172 0.7884287  0.30319483 0.45349789]
 [0.1340417  0.40311299 0.20345524 0.26231334]
 [0.75036467 0.28040876 0.48519097 0.9807372 ]]


we can generate numbers 0<x<10 by multiplying by 10

In [24]:
# run this multiple times each time you will get a different set of numbers (different array) which is what we want
a = rg.random((2,3))*10
print(a)

[[0.39592877 5.28589263 4.59335883]
 [0.62349579 6.41328169 8.52632838]]


## Random Integers
if we want integer we can floor

In [27]:
b = np.floor(2.6)
print(b)

2.0


In [11]:
a = np.floor(rg.random((2,3))*10)
print(a)

[[5. 1. 6.]
 [7. 6. 9.]]


Be mindful as the order makes a big difference, for example the following will always get us an array of 0s

In [29]:
a = np.floor(rg.random((2,3)))*10
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


We can call functions such as sort, sqrt and exp on the entire array efficiently

In [13]:
a = np.floor(rg.random((3,))*10)
print(a)
print(np.sort(a))

[5. 2. 8.]
[2. 5. 8.]


In [14]:
print(np.exp(a))
print(np.sqrt(a))

[ 148.4131591     7.3890561  2980.95798704]
[2.23606798 1.41421356 2.82842712]


## Generating an array of 1s or 0s

In [43]:
a = np.ones(6)
print(a)
b = np.zeros((2,1))
print(b)

[1. 1. 1. 1. 1. 1.]
[[0.]
 [0.]]


In [40]:
b = np.ones((2,6))
print(b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Note that once we moved to multi-dimension we need to provide the space as a tuple (2,6) inside the parenthesis of the ones()

## Arrays Shape

Be mindful to the shape that you are dealing with as often this is the single most common obstacle in any numpy implementation

In [44]:
a = np.ones(6)
print(a)
print(a.shape)

# same as above
a = np.ones((6,))
print(a)
print(a.shape)


[1. 1. 1. 1. 1. 1.]
(6,)
[1. 1. 1. 1. 1. 1.]
(6,)


so the above is an array of one dimension (it is neither a column nor a row)
If we want a column you should do something like the following

In [45]:
a = np.ones((6,1))   # column
print(a)

a = np.ones((1,6))   # row
print(a)


[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 1. 1. 1. 1. 1.]]


Same as for the 0s we can produce as many as we want from them

In [46]:
a = np.zeros(6)
print(a)

[0. 0. 0. 0. 0. 0.]


The following generates an error, make sure to remember this as it will come handy when you forget about the extra parenthesis needed for the shape (6,2)

In [20]:
#a = np.zeros(6,2)
#print(a)

## We can transpose an array to flip its shape

In [47]:
a = np.floor(rg.random((2,3))*10)
print(a)
print(a.T)   # array transpose

[[1. 0. 8.]
 [8. 8. 4.]]
[[1. 8.]
 [0. 8.]
 [8. 4.]]


## We can create an identity matrix

In [20]:
a = np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


For identity matrix we have always that a.T=a

In [23]:
print(a.T)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


## We can assign multiple elements at once

In [48]:
a = np.sort(np.floor(rg.random((10,))*10))
print(a)

a[2:6] = 1000
print(a)

a[2:6] = np.ones(6-2)
print(a)

[0. 2. 2. 2. 6. 6. 7. 8. 8. 9.]
[   0.    2. 1000. 1000. 1000. 1000.    7.    8.    8.    9.]
[0. 2. 1. 1. 1. 1. 7. 8. 8. 9.]


## Function calls

In [22]:

def f(x,y):
    return x+y  
    #return x    # uncomment to try me but comment the others
    #return y    # same as above
    #return x*y  # same as above

b = np.fromfunction(f,(5,4),dtype=int)
print(b)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


## Concatenate and merge arrays along any axis

In [49]:
a = np.floor(10*rg.random((2,5)))
b = np.floor(10*rg.random((2,5)))
print(a)
print(b)
d = np.c_[a,b]    # merged along the columns
print(d)


[[1. 4. 8. 4. 5.]
 [0. 6. 9. 8. 8.]]
[[6. 2. 7. 2. 8.]
 [0. 8. 1. 3. 3.]]
[[1. 4. 8. 4. 5. 6. 2. 7. 2. 8.]
 [0. 6. 9. 8. 8. 0. 8. 1. 3. 3.]]


In [25]:
print (a)
print (b)
d = np.c_[a.T,b.T].T    # merged along the rows
print(d)

[[0. 6. 7. 8. 2.]
 [2. 6. 8. 9. 1.]]
[[4. 8. 4. 5. 0.]
 [6. 9. 8. 8. 6.]]
[[0. 6. 7. 8. 2.]
 [2. 6. 8. 9. 1.]
 [4. 8. 4. 5. 0.]
 [6. 9. 8. 8. 6.]]


In [26]:
print (a)
print (b)
d = np.r_[a,b]        # merged along the rows
print(d)

[[0. 6. 7. 8. 2.]
 [2. 6. 8. 9. 1.]]
[[4. 8. 4. 5. 0.]
 [6. 9. 8. 8. 6.]]
[[0. 6. 7. 8. 2.]
 [2. 6. 8. 9. 1.]
 [4. 8. 4. 5. 0.]
 [6. 9. 8. 8. 6.]]


The above can be achieved in many ways, we show some below

In [51]:
d = np.hstack((a,b))  # merged along the columns
print(a)
print(b)
print('--')
print(d)

[[1. 4. 8. 4. 5.]
 [0. 6. 9. 8. 8.]]
[[6. 2. 7. 2. 8.]
 [0. 8. 1. 3. 3.]]
--
[[1. 4. 8. 4. 5. 6. 2. 7. 2. 8.]
 [0. 6. 9. 8. 8. 0. 8. 1. 3. 3.]]


In [54]:
d = np.vstack((a,b))  # merged along the rows
print(d)

[[1 2 3]
 [4 5 6]]


In [58]:
d = np.column_stack((a,b))   # merged along the columns
print(a)
print(b)
print('--')
print(d)

[1 2 3]
[4 5 6]
--
[[1 4]
 [2 5]
 [3 6]]


In [52]:
a = np.array((1,2,3))
b = np.array((4,5,6))
d = np.column_stack((a,b))
print(a)
print(b)
print(d)


[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


## Flattening an Array

In [31]:
print(d)
print(d.ravel())

[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]


## Making Copies and Pass by Reference

Numpy passed to functions and assign by object reference which means assignment can produce surprising results and you must be aware of this

In [59]:
h = d
print(h)

[[1 4]
 [2 5]
 [3 6]]


In [60]:
d[0,0] = 100
print(h) 
print(d) 
print(d is h)

[[100   4]
 [  2   5]
 [  3   6]]
[[100   4]
 [  2   5]
 [  3   6]]
True


So both h and d are **pointing to the same array in memory** if you change one you are changing the other !!!!

## Broadcasting, Matrices and Arrays Multiplication

### Multiplication

**This is an important topic that we will make use of in later units. Make sure to understand it. See official documentation of numpy [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting) for more details.**

First we have to realise that array multiplication is different than matrix multiplication in numpy.
Numpy multiply element-wise when we simply use the operators * . For example:

In [66]:
a = np.array((1,2,3))
b = np.array((4,5,6))
d = a*b
print(d)
print(d.shape)

[ 4 10 18]
(3,)


Same for multi-dimensional array

In [67]:

a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((2,5)))
d = a*b
print(a)
print(b)
print('x---------------------')
print(d)

[[3. 0. 1. 0. 1.]
 [2. 0. 3. 1. 3.]]
[[3. 2. 4. 3. 4.]
 [1. 2. 0. 4. 1.]]
x---------------------
[[9. 0. 4. 0. 4.]
 [2. 0. 0. 4. 3.]]


To do matrices multiplication we can do either of two things

1- call the dot function

In [28]:
#multiply and sum along the columns of a and b
print (a)
print (b)
d = a.dot(b.T)
print(d)

[[5. 9. 6. 5. 0.]
 [4. 2. 1. 5. 7.]]
[[2. 7. 5. 1. 9.]
 [4. 2. 8. 1. 7.]]
[[108.  91.]
 [ 95.  82.]]


In [30]:
#multiply and sum along the rows of a and b
print (a)
print (b)
d = a.T.dot(b)
print(d)
print(d.shape)

[[5. 9. 6. 5. 0.]
 [4. 2. 1. 5. 7.]]
[[2. 7. 5. 1. 9.]
 [4. 2. 8. 1. 7.]]
[[26. 43. 57.  9. 73.]
 [26. 67. 61. 11. 95.]
 [16. 44. 38.  7. 61.]
 [30. 45. 65. 10. 80.]
 [28. 14. 56.  7. 49.]]
(5, 5)


2 - convert the arrays into numpy matrices and then perform the multiplication operation *

In [69]:
p = np.matrix(a)
q = np.matrix(b)

print(a)
print(p)

[[3. 0. 1. 0. 1.]
 [2. 0. 3. 1. 3.]]
[[3. 0. 1. 0. 1.]
 [2. 0. 3. 1. 3.]]


Now we can do the usual matrices operations 

In [41]:
#multiply and sum along the columns of p and q
p*q.T

matrix([[ 7., 22.],
        [ 7., 13.]])

In [42]:
#multiply and sum along the rows of p and q
p.T*q

matrix([[ 0., 13.,  4., 13., 14.],
        [ 0.,  3.,  0.,  3.,  6.],
        [ 0.,  4.,  1.,  4.,  5.],
        [ 0.,  7.,  1.,  7., 11.],
        [ 0.,  9.,  3.,  9.,  9.]])

### Broadcasting

In [43]:
a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((2,1)))

print(a)
print(b)


[[2. 4. 3. 4. 1.]
 [2. 0. 4. 1. 1.]]
[[0.]
 [1.]]


Let us broadcast b on a

In [44]:
d = a*b
print(d)

[[0. 0. 0. 0. 0.]
 [2. 0. 4. 1. 1.]]


i.e. broadcasting b on a takes each element of the first row of 'a' and multiply it by first row of 'b' and same for the second rows of 'a' and 'b'

note that 'a' and 'b' must agree on one axis and the second axis must have a dimension of 1 to be able to do the broadcasting, for example the following code will produce an error

In [33]:
a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((2,3)))

print(a)
print(b)

# d = a*b  # an error
# print(d)

[[3. 1. 3. 3. 2.]
 [4. 3. 4. 1. 2.]]
[[0. 4. 1.]
 [1. 0. 1.]]


In [46]:
a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((2,5)))

print(a)
print(b)

d = a*b  # element-wise multiplication 
print(d)

[[1. 1. 2. 4. 3.]
 [3. 3. 2. 4. 3.]]
[[2. 0. 2. 1. 0.]
 [2. 3. 1. 3. 2.]]
[[ 2.  0.  4.  4.  0.]
 [ 6.  9.  2. 12.  6.]]


In [47]:
a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((1,5)))

print(a)
print(b)

d = a*b  # broadcasting 
print(d)

[[0. 4. 2. 1. 4.]
 [0. 3. 0. 1. 1.]]
[[4. 1. 4. 3. 3.]]
[[ 0.  4.  8.  3. 12.]
 [ 0.  3.  0.  3.  3.]]
