In [1]:
import numpy as np

In [2]:
a = np.matrix([1,2,3])
b = np.matrix([4,5,6])

In [7]:
a.dot(b.T)

matrix([[32]])

In [13]:
np.concatenate((a,b)).ravel()

matrix([[1, 2, 3, 4, 5, 6]])

In [19]:
a = np.matrix([[1,2],[3,4],[5,6],[7,8]])
b = np.swapaxes(np.swapaxes(a, 0, 1) + np.array([1,2,3,4]), 0, 1)
# a.shape
b

matrix([[ 2,  3],
        [ 5,  6],
        [ 8,  9],
        [11, 12]])

In [21]:
a

matrix([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [22]:
np.swapaxes(a,0,1)

matrix([[1, 3, 5, 7],
        [2, 4, 6, 8]])

In [26]:
c = a + np.array([1,2,3,4]).reshape([4,1])
c

matrix([[ 2,  3],
        [ 5,  6],
        [ 8,  9],
        [11, 12]])

In [27]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [42]:
import random

def HelloRandom(s):
    out = ""
    r = random.randint(1, len(s))
#     print(r)
    for n in range( r ):
        out += s[random.randint(0,r-1)]
#         print(r-1)
    return [out, r]

output = []
for i in range(10):
    output += HelloRandom('Bravo')

print('o' in output)

False


In [43]:
print(output)

['B', 1, 'aavr', 4, 'BBr', 3, 'B', 1, 'B', 1, 'aavBv', 5, 'rr', 2, 'rBr', 3, 'B', 1, 'vvBv', 4]


In [47]:
my_dict = {'test1' : 2, 'test3' : 4}
print(type({x for x in my_dict}))

<class 'set'>


In [53]:
for i in range(2,2):
    print(i)

In [102]:
def sum_of_numbers (n):
    i = 2
    total = 0
    count = 0
    while count < n:
        for j in range(2, i//2 + 1):
            if i%j == 0:
                break
        else:
            total += i
            count += 1
        i += 1
    return total

In [108]:
outputs = []
for n in range(99, 101):
    outputs += (n, sum_of_numbers(n))

outputs

[99, 23592, 100, 24133]

In [112]:
def ripple(L):
    M = [L[0]]*len(L)
    print(M)
    for i in range(len(L)-1):
        M[i+1] = L[i+1] + M[i]
    return M

In [118]:
ripple([1,-3,2,4])

[1, 1, 1, 1]


[1, -2, 0, 4]

In [125]:
import random

output=[]
for i in range(10000):
    # Set temp to random value in range 1-100.
    temp = random.randint(1, 100)
    # Check whether temp is in tolerable range.
    if (temp > 16 or temp < 27):
      output += (temp,  "Temperature tolerable. :)")
    else:
      output += (temp, "Temperature intolerable. :(")

print("Temperature intolerable. :()" in output)

False


In [132]:
def set_analysis(s):
    L = list(s)
    if not L == sorted(L):
        return False
    return set([(L.count(x),x) for x in L ])

m_set = {(3, 'x'), (1, '4'), (3, 'u'), (2, 'e'), (1, 'c')}

set_analysis('4ceeuuuxxx') == m_set
# set_analysis('xxx4uuueec')

True

In [134]:
def number_check(x, y, z):
    if not isinstance(x, int): 
        return False
    return 1 < x < y and x == z and x*y*z == 12 

number_check(2,3,2)

True

In [138]:
def rmtt(s):
    if '-' in s or "'" in s:
        return False
    if not s.islower():
        return False
    s = s.replace('//', '-').title()
    s = s.replace('-And-', " 'n' ")
    return s
# "Steak ‘n’ Chips"

rmtt('steak//and//chips')

"Steak 'n' Chips"

In [144]:
a=b=[]

In [145]:
a += 'a'
b

['a']

In [146]:
id(a) == id(b)

True

In [147]:
a is b

True

In [150]:
a=b=None
a= 'test'
b

In [151]:
a is b

False

In [156]:
output = []
output.extend(['a']*2)
output.extend(['b']*3)
output.extend(['1']*3)
output

['a', 'a', 'b', 'b', 'b', '1', '1', '1']

In [157]:
np.sqrt(512)

22.627416997969522

In [159]:
23**2

529

In [190]:
import random

def f1(x):
    return 2*x

def f2(x):
    return x**2 + 1

def f3(x):
    return 2**x + 2

def f4(x):
    return x**3 + 3

def ranf(n):
    if not type(n) == int:
        return False
    r = random.randint(0,3)
    random_function = [f1,f2,f3,f4][r]
    return random_function(n)

RANDOM = random.randint(1,1000)

n=256
print(f1(n))
print(f2(n))
print(f3(n))
print(f4(n))

512
65537
115792089237316195423570985008687907853269984665640564039457584007913129639938
16777219


In [191]:
def xyx( s ):
    return len(s) < 2 or ( s[0] == s[-1] and xyx( s[1: -1] ) ) 

def xyx_key(n):
    s = str(n)
    l = len(s)
    if xyx(s) and l%2==0:
        return int( s[:int(l/2)] )
    return False

# 54631

xyx_key(5463113645)

54631

In [192]:
import pandas as pd

df = pd.DataFrame()
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [193]:
nums = [89, 111, 117, 32, 97, 114,101, 32, 115, 109, 97,114,116,33]

print("".join([chr(c) for c in nums]) )

You are smart!
