In [1]:
import numpy as np

In [4]:
s1_actions = np.array([.1,.4,.0,.3])
s1_actions

array([0.1, 0.4, 0. , 0.3])

In [5]:
print(np.exp(s1_actions)/np.exp(s1_actions).sum())

[0.22340882 0.30157037 0.20214866 0.27287215]


In [7]:
Q_table = [[.0,.1,.0,.3],
           [.1,.4,.0,.3],
           [.2,.0,.0,.5],
           [.0,.2,.1,.0],
           [.2,.1,.3,.0],
           [0,0,0,0]]
Q_table = np.array(Q_table)
Q_table

array([[0. , 0.1, 0. , 0.3],
       [0.1, 0.4, 0. , 0.3],
       [0.2, 0. , 0. , 0.5],
       [0. , 0.2, 0.1, 0. ],
       [0.2, 0.1, 0.3, 0. ],
       [0. , 0. , 0. , 0. ]])

In [22]:
for i,s in enumerate(Q_table):
    print(f'S{i}: {s.sum()/4}')

S0: 0.1
S1: 0.2
S2: 0.175
S3: 0.07500000000000001
S4: 0.15000000000000002
S5: 0.0
